version: '3.7'
#어떤 v

services:
  postgres-container:
    container_name: DataBase
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: '1234'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - test-networks

  pensive_jackson:
    container_name: server
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/usr/src/bicyclebusan2
      - /usr/src/bicyclebusan2/node_modules
    ports:
      - 3001:3001
    restart: always
    command: yarn start:debug
    networks:
      - test-networks

  dev_redis:
    container_name: redis
    image: redis:latest
    hostname: localhost
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/acl/users.acl:/etc/redis/users.acl
    networks:
      - test-networks

networks:
  test-networks:
    driver: bridge
