version: '3.7'
#어떤 v

services:
  pensive_jackson:
    container_name: server
    build:
      context: .
      dockerfile: dockerfile
      target: runner
    # image: jimin8830/bicyclebusan:latest #허브 만들고 레파지토리 이름
    volumes:
      - .:/usr/src/bicyclebusan2/app
      - /usr/src/bicyclebusan2/app/node_modules
    ports:
      - 3001:3001
    restart: always
    networks:
      - test-networks

  dev_redis:
    container_name: redis
    image: redis:latest
    hostname: localhost
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/acl/users.acl:/etc/redis/users.acl
    networks:
      - test-networks

networks:
  test-networks:
    driver: bridge
