[
  {
    gugun: '부산광역시 해운대구',
    pumpGubun: '태양광',
    pumpSetCost: '1730000',
    spot: '지하철 장산역 5번 출구 주변',
  },
  {
    gugun: '부산광역시 해운대구',
    pumpGubun: '태양광',
    pumpSetCost: '1730000',
    spot: '지하철 영산대역 2번 출구',
  },
  {
    gugun: '부산광역시 해운대구',
    pumpGubun: '태양광',
    pumpSetCost: '1730000',
    spot: '해운대도서관',
  },
  {
    gugun: '부산광역시 해운대구',
    pumpGubun: '태양광',
    pumpSetCost: '1730000',
    spot: '수영강변 좌수영교 하부(해운대구 자전거 종합서비스센터 앞)',
  },
  {
    gugun: '부산광역시 해운대구',
    pumpGubun: '태양광',
    pumpSetCost: '1730000',
    spot: '옛 해운대역(기차역) 광장',
  },
  {
    gugun: '부산광역시 해운대구',
    pumpGubun: '태양광',
    pumpSetCost: '1730000',
    spot: '지하철 장산역 6번 출구 주변',
  },
  {
    gugun: '부산광역시 해운대구',
    pumpGubun: '태양광',
    pumpSetCost: '1730000',
    spot: '해운대구청 정문 자전거 보관대 옆',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '영선동 남항대교 하부',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '대평초등학교 맞은편',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '대교동 인제요양병원 앞',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '봉래동 미광아파트 앞',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '봉래시장 앞',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '산업도로 (주)거청 맞은편',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '동삼1동 사격장앞',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '어울림문화공원 후문',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '해양대학교 입구',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '부산대교 공영주차장 옆',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '영선동 주유소 맞은편',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '영선동 부산은행 맞은 편',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '동부산아이존빌아파트 앞',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '해동병원 맞은편 버스정류장 앞',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '봉래동 부산은행 맞은편',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '영선동 부산은행 앞',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '영선동 롯데리아 앞',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '청학동 수변공원 입구',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '태양광',
    pumpSetCost: '4300000',
    spot: '동삼혁신지구내 농구장 옆',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '동삼해수천 축구장옆',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: 'SK부산저유소 정류소 앞',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '535000',
    spot: '한진중공업 버스정류소 옆',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '수동식',
    pumpSetCost: '40000',
    spot: '한성맨션 버스정류소 옆',
  },
  {
    gugun: '부산광역시 영도구',
    pumpGubun: '태양광',
    pumpSetCost: '2500000',
    spot: 'X-Sports 광장',
  },
  {
    gugun: '부산광역시 연제구',
    pumpGubun: '태양광',
    pumpSetCost: '1799000',
    spot: '지하철 시청역 5번 출구 자전거보관대 인근',
  },
  {
    gugun: '부산광역시 연제구',
    pumpGubun: '태양광',
    pumpSetCost: '1799000',
    spot: '지하철 거제역 2번 출구 자전거보관대 인근',
  },
  {
    gugun: '부산광역시 연제구',
    pumpGubun: '태양광',
    pumpSetCost: '1799000',
    spot: '지하철 종합운동장역 4번 출구 자전거보관대 인근',
  },
  {
    gugun: '부산광역시 연제구',
    pumpGubun: '태양광',
    pumpSetCost: '1799000',
    spot: '지하철 교대역 6번 출구 자전거보관대 인근',
  },
  {
    gugun: '부산광역시 연제구',
    pumpGubun: '태양광',
    pumpSetCost: '1799000',
    spot: '거제2동 종합사회복지관',
  },
  {
    gugun: '부산광역시 연제구',
    pumpGubun: '태양광',
    pumpSetCost: '1799000',
    spot: '온천천 안락교(연산9동) 자전거보관대 인근',
  },
  {
    gugun: '부산광역시 연제구',
    pumpGubun: '태양광',
    pumpSetCost: '1799000',
    spot: '연산9동 망미주공아파트 자전거보관대 인근',
  },
  {
    gugun: '부산광역시 연제구',
    pumpGubun: '태양광',
    pumpSetCost: '1799000',
    spot: '지하철 배산역 3번 출구 자전거보관대 인근',
  },
  {
    gugun: '부산광역시 연제구',
    pumpGubun: '태양광',
    pumpSetCost: '1799000',
    spot: '지하철 물만골역 4번 출구 자전거보관대 인근',
  },
  {
    gugun: '부산광역시 연제구',
    pumpGubun: '태양광',
    pumpSetCost: '1799000',
    spot: '연산2동 이마트 연제점',
  },
  {
    gugun: '부산광역시 연제구',
    pumpGubun: '태양광',
    pumpSetCost: '1799000',
    spot: '거제1동 홈플러스 아시아드점',
  },
  {
    gugun: '부산광역시 연제구',
    pumpGubun: '태양광',
    pumpSetCost: '1799000',
    spot: '연산1동 홈플러스 연산점',
  },
  {
    gugun: '부산광역시 연제구',
    pumpGubun: '태양광',
    pumpSetCost: '1799000',
    spot: '지하철 연산역 14번출구 자전거보관대 인근',
  },
  {
    gugun: '부산광역시 연제구',
    pumpGubun: '태양광',
    pumpSetCost: '1799000',
    spot: '지하철 교대역 3번출구 국제신문 앞 자전거보관대 인근',
  },
  {
    gugun: '부산광역시 연제구',
    pumpGubun: '태양광',
    pumpSetCost: '1799000',
    spot: '부산교육대학교 후문 입구',
  },
  {
    gugun: '부산광역시 수영구',
    pumpGubun: '태양광',
    pumpSetCost: '1894000',
    spot: '남천동 자전거대여소',
  },
  {
    gugun: '부산광역시 수영구',
    pumpGubun: '태양광',
    pumpSetCost: '2125000',
    spot: '광안대교 하부',
  },
  {
    gugun: '부산광역시 수영구',
    pumpGubun: '태양광',
    pumpSetCost: '2125000',
    spot: '민락동 바다마루 건너편 드림로드',
  },
  {
    gugun: '부산광역시 수영구',
    pumpGubun: '태양광',
    pumpSetCost: '1894000',
    spot: '수영강변 협성르네상스 207동 앞',
  },
  {
    gugun: '부산광역시 수영구',
    pumpGubun: '수동식',
    pumpSetCost: '544500',
    spot: '광안대교 하부',
  },
  {
    gugun: '부산광역시 사하구',
    pumpGubun: '전기식',
    pumpSetCost: '200000',
    spot: '부산광역시 사하구 낙동남로1233번길 38(을숙도 자전거 무료대여소)',
  },
  {
    gugun: '부산광역시 사하구',
    pumpGubun: '수동식',
    pumpSetCost: '30000',
    spot: '부산광역시 사하구 낙동남로1233번길 38(을숙도 자전거 무료대여소)',
  },
  {
    gugun: '부산광역시 사상구',
    pumpGubun: '전기식',
    pumpSetCost: '5600000',
    spot: '감전역 3번 출구',
  },
  {
    gugun: '부산광역시 사상구',
    pumpGubun: '전기식',
    pumpSetCost: '5600000',
    spot: '주례역 1번 출구',
  },
  {
    gugun: '부산광역시 사상구',
    pumpGubun: '수동식',
    pumpSetCost: '600000',
    spot: '사상달리미 자전거대여소',
  },
  {
    gugun: '부산광역시 사상구',
    pumpGubun: '수동식',
    pumpSetCost: '600000',
    spot: '르네시떼역 경전철 아래',
  },
  {
    gugun: '부산광역시 사상구',
    pumpGubun: '수동식',
    pumpSetCost: '600000',
    spot: '국토종주자전거길 전망대쉼터',
  },
  {
    gugun: '부산광역시 사상구',
    pumpGubun: '수동식',
    pumpSetCost: '600000',
    spot: '삼락생태공원 입구 낙동제방위',
  },
  {
    gugun: '부산광역시 북구',
    pumpGubun: '태양광',
    pumpSetCost: '1834000',
    spot: '구포동 도시철도 구포역 자전거 보관대',
  },
  {
    gugun: '부산광역시 북구',
    pumpGubun: '태양광',
    pumpSetCost: '4500000',
    spot: '화명동 화명도서관',
  },
  {
    gugun: '부산광역시 부산진구',
    pumpGubun: '태양광',
    pumpSetCost: '1650000',
    spot: '부산진구청',
  },
  {
    gugun: '부산광역시 부산진구',
    pumpGubun: '태양광',
    pumpSetCost: '1650000',
    spot: '서면신한은행 앞',
  },
  {
    gugun: '부산광역시 부산진구',
    pumpGubun: '태양광',
    pumpSetCost: '2200000',
    spot: '서면역7번출구 앞',
  },
  {
    gugun: '부산광역시 부산진구',
    pumpGubun: '태양광',
    pumpSetCost: '1650000',
    spot: '서면한솔폴라리스 앞',
  },
  {
    gugun: '부산광역시 부산진구',
    pumpGubun: '태양광',
    pumpSetCost: '1650000',
    spot: '부암역6번출구 앞',
  },
  {
    gugun: '부산광역시 부산진구',
    pumpGubun: '태양광',
    pumpSetCost: '1650000',
    spot: '양정역1번출구 앞',
  },
  {
    gugun: '부산광역시 부산진구',
    pumpGubun: '태양광',
    pumpSetCost: '1210000',
    spot: '국민건강보험공단 앞',
  },
  {
    gugun: '부산광역시 부산진구',
    pumpGubun: '태양광',
    pumpSetCost: '1995000',
    spot: '신개금엘지아파트 상가동 앞',
  },
  {
    gugun: '부산광역시 부산진구',
    pumpGubun: '태양광',
    pumpSetCost: '1650000',
    spot: '전포역 8번출구 앞',
  },
  {
    gugun: '부산광역시 부산진구',
    pumpGubun: '태양광',
    pumpSetCost: '2200000',
    spot: '가야역 4번출구 앞',
  },
  {
    gugun: '부산광역시 부산진구',
    pumpGubun: '태양광',
    pumpSetCost: '2200000',
    spot: '부산은행 가야점 앞',
  },
  {
    gugun: '부산광역시 부산진구',
    pumpGubun: '태양광',
    pumpSetCost: '1650000',
    spot: '동의대역 3번출구 앞',
  },
  {
    gugun: '부산광역시 부산진구',
    pumpGubun: '태양광',
    pumpSetCost: '1750850',
    spot: '개금역 4번출구 앞',
  },
  {
    gugun: '부산광역시 부산진구',
    pumpGubun: '태양광',
    pumpSetCost: '1750850',
    spot: '범내골역 5번출구 앞',
  },
  {
    gugun: '부산광역시 부산진구',
    pumpGubun: '태양광',
    pumpSetCost: '2154000',
    spot: '범일역 12번출구 앞',
  },
  {
    gugun: '부산광역시 부산진구',
    pumpGubun: '태양광',
    pumpSetCost: '2154000',
    spot: '범천2동 舊)창공원 앞',
  },
  {
    gugun: '부산광역시 부산진구',
    pumpGubun: '태양광',
    pumpSetCost: '1650000',
    spot: '연지동 국악원 앞',
  },
  {
    gugun: '부산광역시 부산진구',
    pumpGubun: '태양광',
    pumpSetCost: '1750850',
    spot: '범천동 사학연금매장 앞',
  },
  {
    gugun: '부산광역시 동래구',
    pumpGubun: '전기식',
    pumpSetCost: '1925000',
    spot: '동래구청(임시청사)',
  },
  {
    gugun: '부산광역시 동래구',
    pumpGubun: '전기식',
    pumpSetCost: '1925000',
    spot: '금강공원 공영주차장',
  },
  {
    gugun: '부산광역시 동래구',
    pumpGubun: '태양광',
    pumpSetCost: '2000000',
    spot: '안락교차로(기업은행앞)',
  },
  {
    gugun: '부산광역시 동래구',
    pumpGubun: '태양광',
    pumpSetCost: '2000000',
    spot: '사직운동장앞(사직자이아파트 맞은편)',
  },
  {
    gugun: '부산광역시 동래구',
    pumpGubun: '태양광',
    pumpSetCost: '2000000',
    spot: '도시철도 온천장역 3번출구 옆',
  },
  {
    gugun: '부산광역시 남구',
    pumpGubun: '태양광',
    pumpSetCost: '1990000',
    spot: 'UN조각공원 입구',
  },
  {
    gugun: '부산광역시 남구',
    pumpGubun: '태양광',
    pumpSetCost: '1990000',
    spot: '분포로 수변공원',
  },
  {
    gugun: '부산광역시 남구',
    pumpGubun: '태양광',
    pumpSetCost: '1990000',
    spot: '문현동 270-4',
  },
  {
    gugun: '부산광역시 남구',
    pumpGubun: '태양광',
    pumpSetCost: '1990000',
    spot: '대연고개 맞은편',
  },
  {
    gugun: '부산광역시 기장군',
    pumpGubun: '태양광',
    pumpSetCost: '1802000',
    spot: '군청사내',
  },
  {
    gugun: '부산광역시 기장군',
    pumpGubun: '태양광',
    pumpSetCost: '1802000',
    spot: '정관면사무소',
  },
  {
    gugun: '부산광역시 기장군',
    pumpGubun: '태양광',
    pumpSetCost: '1802000',
    spot: '일광면사무소',
  },
  {
    gugun: '부산광역시 기장군',
    pumpGubun: '태양광',
    pumpSetCost: '1895000',
    spot: '기장군청 앞',
  },
  {
    gugun: '부산광역시 기장군',
    pumpGubun: '태양광',
    pumpSetCost: '1895000',
    spot: '정관 어린이도서관',
  },
  {
    gugun: '부산광역시 기장군',
    pumpGubun: '태양광',
    pumpSetCost: '2180000',
    spot: '좌광천 중앙교 인근',
  },
  {
    gugun: '부산광역시 기장군',
    pumpGubun: '태양광',
    pumpSetCost: '2180000',
    spot: '좌광천 달음교 인근',
  },
  {
    gugun: '부산광역시 기장군',
    pumpGubun: '태양광',
    pumpSetCost: '2200000',
    spot: '일광면 국민체육센터',
  },
  {
    gugun: '부산광역시 기장군',
    pumpGubun: '태양광',
    pumpSetCost: '2200000',
    spot: '정관 돌고래분수광장',
  },
  {
    gugun: '부산광역시 기장군',
    pumpGubun: '태양광',
    pumpSetCost: '2200000',
    spot: '한신더휴1단지&자이푸르지오2단지 교차로',
  },
  {
    gugun: '부산광역시 기장군',
    pumpGubun: '태양광',
    pumpSetCost: '2200000',
    spot: '일광역 광장',
  },
  {
    gugun: '부산광역시 기장군',
    pumpGubun: '태양광',
    pumpSetCost: '2200000',
    spot: '좌광천 중앙교 공중화장실 인근',
  },
  {
    gugun: '부산광역시 기장군',
    pumpGubun: '태양광',
    pumpSetCost: '2200000',
    spot: '모전마을 정류소[16042] 인근',
  },
  {
    gugun: '부산광역시 기장군',
    pumpGubun: '태양광',
    pumpSetCost: '2200000',
    spot: '철마면 안평역 3번출구',
  },
  {
    gugun: '부산광역시 기장군',
    pumpGubun: '태양광',
    pumpSetCost: '2420000',
    spot: '일광신도시 이편한세상 상가 앞 횡단보도 부근',
  },
  {
    gugun: '부산광역시 기장군',
    pumpGubun: '태양광',
    pumpSetCost: '3630000',
    spot: '일광해수욕장 공중화장실 앞',
  },
  {
    gugun: '부산광역시 기장군',
    pumpGubun: '태양광',
    pumpSetCost: '3630000',
    spot: '임랑행정봉사실 앞',
  },
  {
    gugun: '부산광역시 금정구',
    pumpGubun: '수동식',
    pumpSetCost: '10000',
    spot: '온천장역 자전거 대여소',
  },
  {
    gugun: '부산광역시 강서구',
    pumpGubun: '태양광(소형)',
    pumpSetCost: '1,833,000',
    spot: '강서구청사',
  },
  {
    gugun: '부산광역시 강서구',
    pumpGubun: '태양광(소형)',
    pumpSetCost: '1,833,000',
    spot: '강서구청지하철역',
  },
  {
    gugun: '부산광역시 강서구',
    pumpGubun: '태양광(소형)',
    pumpSetCost: '1,833,000',
    spot: '한국농어촌공사부산지소',
  },
  {
    gugun: '부산광역시 강서구',
    pumpGubun: '태양광(소형)',
    pumpSetCost: '1,990,000',
    spot: '지사민원센터',
  },
  {
    gugun: '부산광역시 강서구',
    pumpGubun: '태양광(소형)',
    pumpSetCost: '1,995,000',
    spot: '대저생태공원(등구입구)',
  },
  {
    gugun: '부산광역시 강서구',
    pumpGubun: '태양광(소형)',
    pumpSetCost: '1,995,000',
    spot: '맥도생태공원(관리사무소)',
  },
  {
    gugun: '부산광역시 강서구',
    pumpGubun: '태양광(소형)',
    pumpSetCost: '2,450,000',
    spot: '대저2동 주민센터',
  },
  {
    gugun: '부산광역시 강서구',
    pumpGubun: '태양광(중형)',
    pumpSetCost: '3,300,000',
    spot: '명지새동네(명지동 1-723번지)',
  },
  {
    gugun: '부산광역시 강서구',
    pumpGubun: '태양광(중형)',
    pumpSetCost: '3,300,000',
    spot: '명지 철새탐조대(명지동 3309)',
  },
  {
    gugun: '부산광역시 강서구',
    pumpGubun: '태양광(중형)',
    pumpSetCost: '3,300,000',
    spot: '신호동 해안산책로(신호동 263)',
  },
  {
    gugun: '부산광역시 강서구',
    pumpGubun: '태양광(중형)',
    pumpSetCost: '3,300,000',
    spot: '녹산산단해안산책로(송정동 1767번지)',
  },
  {
    gugun: '낙동강관리본부',
    pumpGubun: '수동식',
    pumpSetCost: '10000',
    spot: '삼락자전거대여소',
  },
  {
    gugun: '낙동강관리본부',
    pumpGubun: '전기식(콤프레샤)',
    pumpSetCost: '150000',
    spot: '화명 자전거대여소 앞',
  },
  {
    gugun: '낙동강관리본부',
    pumpGubun: '수동식',
    pumpSetCost: '10000',
    spot: '대저 자전거대여소',
  },
  {
    gugun: '낙동강관리본부',
    pumpGubun: '수동식',
    pumpSetCost: '10000',
    spot: '맥도 자전거무료대여소',
  },
  {
    gugun: '낙동강관리본부',
    pumpGubun: '수동식',
    pumpSetCost: '10000',
    spot: '맥도 철새태마공원',
  },
];
